export const CREATE_WORKSPACE_MODAL_KEY = Symbol('CREATE_WORKSPACE_MODAL');
export const CREATE_PROJECT_MODAL_KEY = Symbol('CREATE_PROJECT_MODAL');
export const CREATE_TEST_SUITE_MODAL_KEY = Symbol('CREATE_TEST_SUITE_MODAL');
export const CREATE_TEST_CASE_MODAL_KEY = Symbol('CREATE_TEST_CASE_MODAL');