import {
  Activity,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  Clipboard,
  Cloud,
  Code,
  Compass,
  Cpu,
  Database,
  Flag,
  FolderOpen,
  GitBranch,
  Globe,
  Heart,
  Home,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Monitor,
  Package,
  Paperclip,
  PenTool,
  Phone,
  PieChart,
  Rocket,
  Search,
  Settings,
  Shield,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsUp,
  Trash,
  TrendingUp,
  Users,
  Wallet
} from '@lucide/svelte';

export const icons = [
	{ name: 'Building2', component: Building2 },
	{ name: 'Briefcase', component: Briefcase },
	{ name: 'Users', component: Users },
	{ name: 'Target', component: Target },
	{ name: 'BarChart3', component: BarChart3 },
	{ name: 'TrendingUp', component: TrendingUp },
	{ name: 'Activity', component: Activity },
	{ name: 'PieChart', component: PieChart },
	{ name: 'Code', component: Code },
	{ name: 'GitBranch', component: GitBranch },
	{ name: 'Database', component: Database },
	{ name: 'Cpu', component: Cpu },
	{ name: 'Cloud', component: Cloud },
	{ name: 'Settings', component: Settings },
	{ name: 'Home', component: Home },
	{ name: 'FolderOpen', component: FolderOpen },
	{ name: 'Globe', component: Globe },
	{ name: 'MapPin', component: MapPin },
	{ name: 'Heart', component: Heart },
	{ name: 'Rocket', component: Rocket },
	{ name: 'Calendar', component: Calendar },
	{ name: 'Clipboard', component: Clipboard },
	{ name: 'Compass', component: Compass },
	{ name: 'Flag', component: Flag },
	{ name: 'Lightbulb', component: Lightbulb },
	{ name: 'Lock', component: Lock },
	{ name: 'Mail', component: Mail },
	{ name: 'Monitor', component: Monitor },
	{ name: 'Package', component: Package },
	{ name: 'Paperclip', component: Paperclip },
	{ name: 'PenTool', component: PenTool },
	{ name: 'Phone', component: Phone },
	{ name: 'Search', component: Search },
	{ name: 'Shield', component: Shield },
	{ name: 'Star', component: Star },
	{ name: 'Sun', component: Sun },
	{ name: 'Tag', component: Tag },
	{ name: 'ThumbsUp', component: ThumbsUp },
	{ name: 'Trash', component: Trash },
	{ name: 'Wallet', component: Wallet }
];

export const getIcon = (name: string) => {
	return icons.find((icon) => icon.name === name)?.component;
};
